version: '3.1'

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    image: scidas/slurm.controller:19.05.1
    container_name: controller
    privileged: true
    volumes:
      - home:/home
      - secret:/.secret
      - ./modules:/opt/apps/Linux
      - ./modulefiles:/opt/apps/modulefiles/Linux
    restart: always
    hostname: controller.local.dev
    networks:
      - slurm
    environment:
      USE_SLURMDBD: 'true'
      CLUSTER_NAME: snowflake
      CONTROL_MACHINE: controller
      SLURMCTLD_PORT: 6817
      SLURMD_PORT: 6818
      ACCOUNTING_STORAGE_HOST: database
      ACCOUNTING_STORAGE_PORT: 6819
      COMPUTE_NODES: worker01 worker02
      PARTITION_NAME: docker

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: scidas/slurm.database:19.05.1
    depends_on:
      - controller
    container_name: database
    privileged: true
    volumes:
      - home:/home
      - secret:/.secret
    restart: always
    hostname: database.local.dev
    networks:
      - slurm
    environment:
      DBD_ADDR: database
      DBD_HOST: database
      DBD_PORT: 6819
      STORAGE_HOST: database.local.dev
      STORAGE_PORT: 3306
      STORAGE_PASS: password
      STORAGE_USER: slurm

  worker01:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: scidas/slurm.worker:19.05.1
    depends_on:
      - controller
    container_name: worker01
    privileged: true
    volumes:
      - home:/home
      - secret:/.secret
      - ./modules:/opt/apps/Linux
      - ./modulefiles:/opt/apps/modulefiles/Linux
    restart: always
    hostname: worker01.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller
      ACCOUNTING_STORAGE_HOST: database
      COMPUTE_NODES: worker01 worker02

  worker02:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: scidas/slurm.worker:19.05.1
    depends_on:
      - controller
    container_name: worker02
    privileged: true
    volumes:
      - home:/home
      - secret:/.secret
      - ./modules:/opt/apps/Linux
      - ./modulefiles:/opt/apps/modulefiles/Linux
    restart: always
    hostname: worker02.local.dev
    networks:
      - slurm
    environment:
      CONTROL_MACHINE: controller
      ACCOUNTING_STORAGE_HOST: database
      COMPUTE_NODES: worker01 worker02

volumes:
  home:
  secret:

networks:
  slurm:
